#!/usr/bin/env bash
# Script that takes 2 arguments: Domain and subdomain (in that order)
# Outputs 'The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]'

printDetails() {
    cmd=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $cmd" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

subdomains=("www" "lb-01" "web-01" "web-02")

if [ "$#" == 1 ]; then
    for subdomain in "${subdomains[@]}"; do
        printDetails "$1" "$subdomain"
    done
elif [ "$#" == 2 ]; then
    printDetails "$1" "$2"
fi
