#!/usr/bin/env bash
# Automatically installs and configures Nginx to listen on port 80
# Creates a file at the root of the server containing 'Hello World!'
# Redirects /redirect_me to https://github.com using sed
# Configured to use costume error 404 page

apt-get update
apt-get -y install nginx
chmod o+w /var/www/html/
echo "Hello World!" > /var/www/html/index.html

# custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Backup default Nginx configuration
cp /etc/nginx/sites-enabled/default ~/defaultBackup

redirectLine="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com;\n\t}"
errorPage="server_name _;\n\n\terror_page 404 /404.html;\n"

sed -i "s|server_name _;|${redirectLine}|" /etc/nginx/sites-enabled/default
sed -i "s|server_name _;|${errorPage}|" /etc/nginx/sites-enabled/default

service nginx restart
