#!/usr/bin/env bash
# installs and configurs HAproxy on a srrver

#enabling dedicated PPA for installation
apt-get -y update
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8

# installing HAproxy
apt-get -y install haproxy=1.8.\*

# Ensure HAProxy can be managed via an init script
echo "ENABLED=1" > /etc/default/haproxy

# backing up config file
cp /etc/haproxy/haproxy.cfg ~/haproxy.cfg.backup

# configure HAproxy
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 430654-web-01 100.26.239.81:80 check
    server 430654-web-02 54.165.171.31:80 check
" >> /etc/haproxy/haproxy.cfg

# restart service
service haproxy restart
