#!/usr/bin/env bash
# add user

sudo mysql -u root -p -e "CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';

sudo mysql -u root -p -e "GRANT ALL PRIVILEGES ON *.* TO 'holberton_user'@'localhost'; FLUSH PRIVILEGES;"