#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic while allowing traffic
# on ports 22, 443 and 80

sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80