#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

sudo cp /etc/hosts ~/host.modified
echo "127.0.0.2	localhost" > ~/host.modified
echo "8.8.8.8  	facebook.com" >> ~/host.modified
sudo cp -f ~/host.modified /etc/hosts
