#!/usr/bin/env bash
# start nginx using nginx user
# nginx must be listening on all active IPs on port 8080
service nginx stop
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
